# input dir : it should consist detections, original_detections and images folder
input_dir: "/home/datadev/Blurring Stadt Essen/nd/Netherlands project training_4_splitted"

#output dir: it is automatically created with the name of final inside the input dir





