# Input Directory : it should contain 3 folders namely detections,original_detections,images
input_dir: "/home/datadev/Blurring Stadt Essen/nd/Netherlands project training_4"

# It will create 3 folders inside output dir for splitted images and texts namely detections,original_detections,images
output_dir: "/home/datadev/Blurring Stadt Essen/nd/Netherlands project training_4_splitted"

# Image size:
# "4000_8000" or "2400_4800"
image_size: "2400_4800"





